# Site settings
title: yamir.dev
email: yencarnacion@webninjapr.com
description: > # this means to ignore newlines until "baseurl:"
  Yamir's Random Thoughts on the Web
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://yamir.dev" # the base hostname & protocol for your site
twitter_username: yencarnacion
github_username:  yencarnacion

# Build settings
markdown: kramdown
